version: '3'
services:
  jenkins:
    container_name: jenkins
    hostname: myjenkins.local
    image: jenkins/jenkins:latest
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net

# agent:
#   image: jenkins/ssh-agent:jdk11
#     privileged: true
#     user: root
#     container_name: agent
#     expose:
#       - 22
#     environment:
#       - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa

  tomcat:
    container_name: tomcat
    hostname: mytomcat.local
    image: tomcat:latest
    ports:
      - "8081:8080"
    networks:
      - net
   
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      SONARQUBE_USERNAME: admin
      SONARQUBE_PASSWORD: mipassword
    networks:
      - net

volumes:
  jenkins_home:
  
networks:
  net: